version: '3'
services:

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    hostname: kafka 
    container_name: kafka-7.6.0
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_NODE_ID: 1001
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1001@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: '_m3W06fnQJmVcJfI9cDqMA'
    volumes:
      - "/opt/data/kafka/data/data:/tmp/kraft-combined-logs"

  kafka-ui:
    image: provectuslabs/kafka-ui
    hostname: kafka-ui
    container_name: kafka-ui
    depends_on: 
      - kafka
    ports:
      - "9100:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: diplom-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      DYNAMIC_CONFIG_ENABLED: 'true'

  benthos:
    image: ghcr.io/benthosdev/benthos:4.26
    hostname: benthos
    command: -r "/resources/*.yaml" streams /streams/*.yaml
    container_name: benthos-4.26
    depends_on:
      - kafka
    ports:
      - "4195:4195"
    volumes:
      - "./maps:/maps"
      - "./resources:/resources"
      - "./streams:/streams"
