version: '3'
services:

  benthos:
    image: ghcr.io/benthosdev/benthos:4.26
    hostname: benthos
    command: -r "/resources/*.yaml" streams /streams/*.yaml
    container_name: benthos-4.26
    ports:
      - "4195:4195"
    environment:
      KAFKA_HOST: 172.17.0.1:9092
      POSTGRES_DSN: postgres://postgres:postgres@172.17.0.1:5432/diplom?sslmode=disable
    volumes:
      - "./maps:/maps"
      - "./resources:/resources"
      - "./streams:/streams"
