input:
  resource: "test_card_input"

buffer:
  system_window: 
    timestamp_mapping: this.timestamp
    size: 9s
    slide: 3s

pipeline:
  processors:
# Set card metadata
    - mapping: meta card_lost_limit = 1.0
    - switch:
        - check: this.type == "card"
          processors: 
            - group_by_value: 
                value: ${!json("data.id")}

            - resource: card_employee_enrichment_and_save
            
            - workflow:
                order:
                  - [card_lost_event]

output:
  resource: "test_output"