input:
  resource: "test_employee_input"

buffer:
  system_window: 
    timestamp_mapping: this.timestamp
    size: 9s
    slide: 3s

pipeline:
  processors:
    - switch:
        - check: this.type == "employee"
          processors:
            - group_by_value:  
                value: ${!json("data.id")}
            - resource: employee_zone_enrichment_and_save
            
            - workflow:
                order: 
                  - [employee_exceeded_time_limit, employee_access_denided, employee_changed_zone]

# - check: this.type == "employee_changed_zone_event"
#   processors:
#     - resource: employee_changed_zone_event
output:
  resource: "test_output"