input:
  resource: "test_pass_input"

buffer:
  system_window: 
    timestamp_mapping: this.timestamp
    size: 9s
    slide: 3s

pipeline:
  processors:
    - switch:
        - check: this.type == "pass"
          processors:
            - group_by_value: 
                value: ${!json("data.id")}
            - resource: pass_save
output:
  resource: "test_output"